# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Bash@3
  displayName: Install_Run_SAST
   inputs:
   targetType: 'inline'
    script: |
    env | grep -E "AZURE_HTTP_USER_AGENT|BUILD_BUILDID" > /tmp/env
    docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
    docker run --rm --env-file /tmp/env --mount type=bind,source="$PWD",target=/scan  registry.fortidevsec.forticloud.com/fdevsec_sast:latest